src/Entity/Arbre.php
<?php

namespace App\Entity;

use App\Repository\ArbreRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArbreRepository::class)]
class Arbre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateImplentation = null;

    #[ORM\Column]
    private ?bool $aRisque = null;

    #[ORM\ManyToOne(inversedBy: 'arbres')]
    private ?Parc $Parc = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateImplentation(): ?\DateTimeInterface
    {
        return $this->dateImplentation;
    }

    public function setDateImplentation(\DateTimeInterface $dateImplentation): static
    {
        $this->dateImplentation = $dateImplentation;

        return $this;
    }

    public function isARisque(): ?bool
    {
        return $this->aRisque;
    }

    public function setARisque(bool $aRisque): static
    {
        $this->aRisque = $aRisque;

        return $this;
    }

    public function getParc(): ?Parc
    {
        return $this->Parc;
    }

    public function setParc(?Parc $Parc): static
    {
        $this->Parc = $Parc;

        return $this;
    }
}

src/Entity/Parc.php
<?php

namespace App\Entity;

use App\Repository\ParcRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ParcRepository::class)]
class Parc
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\OneToMany(mappedBy: 'Parc', targetEntity: Arbre::class)]
    private Collection $arbres;

    public function __construct()
    {
        $this->arbres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Arbre>
     */
    public function getArbres(): Collection
    {
        return $this->arbres;
    }

    public function addArbre(Arbre $arbre): static
    {
        if (!$this->arbres->contains($arbre)) {
            $this->arbres->add($arbre);
            $arbre->setParc($this);
        }

        return $this;
    }

    public function removeArbre(Arbre $arbre): static
    {
        if ($this->arbres->removeElement($arbre)) {
            // set the owning side to null (unless already changed)
            if ($arbre->getParc() === $this) {
                $arbre->setParc(null);
            }
        }

        return $this;
    }
}

src/Form/ArbreType.php
<?php

namespace App\Form;

use App\Entity\Arbre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use App\Entity\Parc;
class ArbreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dateImplentation',DateType::class)
            ->add('aRisque', CheckboxType::class, [
                'label' => 'Etat', 
                'required' => false,
                'data' => false
            ])
            ->add('Parc',EntityType::class,[
                'class'=>Parc::class,
                'choice_label'=>'nom',
                'multiple' => false
            ])
            ->add('Submit',SubmitType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Arbre::class,
        ]);
    }
}

src/Form/EntretienType.php
<?php

namespace App\Form;

use App\Entity\Candidat;
use App\Entity\Entretien;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
class EntretienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date',DateType::class)
            ->add('etat', CheckboxType::class, [
                'label' => 'Etat', 
                'required' => false,
                'data' => true
            ])
            ->add(
                'type', 
                ChoiceType::class, 
                [
                    'choices' => [
                        'Technique N1' => 'Technique N1',
                        'Technique N2' => 'Technique N2',
                        'Ressources Humaine' => 'Ressources Humaine',
                    ],
                'expanded' => true
                ]
            )
            ->add('candidat',EntityType::class,[
                'class'=>Candidat::class,
                'choice_label'=>'nom',
                'multiple' => false
            ])
            ->add('Submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entretien::class,
        ]);
    }
}

src/Controller/ArbreController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Arbre;
use App\Repository\ParcRepository;
use App\Repository\ArbreRepository;
use App\Form\ArbreType;

class ArbreController extends AbstractController
{
    #[Route('/arbre', name: 'app_arbre')]
    public function index(): Response
    {
        return $this->render('arbre/index.html.twig', [
            'controller_name' => 'ArbreController',
        ]);
    }
    #[Route('/arbre/add', name: 'app_arbre_add')]

public function new(Request $request,ManagerRegistry $manager): Response
{
   $e= new Arbre();
        $form = $this->createForm(ArbreType::class,$e);
        $form->handleRequest($request);
        if($form->isSubmitted())
        {
            $manager->getManager()->persist($e);
            $manager->getManager()->flush();
            return $this->redirectToRoute('app_listarbre');
        }
        return $this->renderForm('arbre/add.html.twig',['f'=>$form]);  
}
#[Route('/arbre/list', name:'app_listarbre')]
public function list(ArbreRepository $repo){
   $e = $repo->findAll();
   return $this->render('arbre/list.html.twig', [
       'arbres' => $e
   ]);
}
}

templates/arbre/add.html.twig
{{form(f)}}

templates/arbre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ArbreController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Youngblood-valo/exam/src/Controller/ArbreController.php'|file_link(0) }}">src/Controller/ArbreController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Youngblood-valo/exam/templates/arbre/index.html.twig'|file_link(0) }}">templates/arbre/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/arbre/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Liste des arbres </h1>
  <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
   <a href="{{ path('app_arbre_add') }}" class="btn btn-primary">New arbre</a>

   {% if arbres is defined and arbres|length > 0 %}
    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>Parc Nom</th>
                <th>date</th>
                <th>A risque?</th>

            </tr>
        </thead>
        <tbody>
            {% for a in arbres %}
                <tr>
                    <td>{{ a.id }}</td>
                    <td>{{ a.parc.nom|upper }}</td>
                    <td>{{ a.dateImplentation|date('Y-m-d H:i:s') }}</td>
                    <td>{% if a.aRisque %}
Oui {% else %}
Non {% endif %}</td>
                   
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    <p class="mt-3">Aucun auteur trouvé.</p>
{% endif %}

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/entretien/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Liste des Entretiens </h1>
  <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
   <a href="{{ path('app_addEntretien') }}" class="btn btn-primary">New Auteur</a>

   {% if entretiens is defined and entretiens|length > 0 %}
    <table class="table table-bordered mt-3">
        <thead>
            <tr>
                <th>ID</th>
                <th>type</th>
                <th>date</th>
                <th>etat</th>
                <th>candidat</th>


            </tr>
        </thead>
        <tbody>
            {% for entretien in entretiens %}
                <tr>
                    <td>{{ entretien.id }}</td>
                    <td>{{ entretien.type|upper }}</td>
                    <td>{{ entretien.date|date('Y-m-d H:i:s') }}</td>
                    <td>{{ entretien.etat }}</td>
                    <td>{{ entretien.candidat.nom }}</td>
            
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    <p class="mt-3">Aucun auteur trouvé.</p>
{% endif %}

{% endblock %}